# Generated by Django 4.1.4 on 2022-12-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0002_feedback_watch_orders'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='watchshopuser',
            managers=[
            ],
        ),
    ]
