# Generated by Django 4.1.4 on 2023-08-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0005_address_order_orderwatch_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='watch_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
