# Generated by Django 4.1.4 on 2023-08-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0006_alter_watch_watch_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.AddField(
            model_name='address',
            name='billing_address_alt',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='billing_adress',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
