# Generated by Django 4.1.4 on 2023-08-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0008_remove_order_address_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
    ]
